AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - node_modules/*

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
